/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FundUtilisationRouteImport } from './routes/fund-utilisation'
import { Route as UlbPerformanceRouteImport } from './routes/ulb-performance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FundUtilisationRoute = FundUtilisationRouteImport.update({
  id: '/fund-utilisation',
  path: '/fund-utilisation',
  getParentRoute: () => rootRouteImport,
} as any)
const UlbPerformanceRoute = UlbPerformanceRouteImport.update({
  id: '/ulb-performance',
  path: '/ulb-performance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fund-utilisation': typeof FundUtilisationRoute
  '/ulb-performance': typeof UlbPerformanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fund-utilisation': typeof FundUtilisationRoute
  '/ulb-performance': typeof UlbPerformanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fund-utilisation': typeof FundUtilisationRoute
  '/ulb-performance': typeof UlbPerformanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fund-utilisation' | '/ulb-performance'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fund-utilisation' | '/ulb-performance'
  id: '__root__' | '/' | '/fund-utilisation' | '/ulb-performance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FundUtilisationRoute: typeof FundUtilisationRoute
  UlbPerformanceRoute: typeof UlbPerformanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund-utilisation': {
      id: '/fund-utilisation'
      path: '/fund-utilisation'
      fullPath: '/fund-utilisation'
      preLoaderRoute: typeof FundUtilisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ulb-performance': {
      id: '/ulb-performance'
      path: '/ulb-performance'
      fullPath: '/ulb-performance'
      preLoaderRoute: typeof UlbPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FundUtilisationRoute: FundUtilisationRoute,
  UlbPerformanceRoute: UlbPerformanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
